hummingbird: #namespace

  # If the running step is too large, then there will be a long time between 2 ctrl cmds
  running_step: 0.01 # amount of time the control will be executed
  num_envs: 1 # We only could use single sim environment for the training
  #learning general params
  n_actions: 4 # We have 4 actions, 4 rotor speed values
  n_observations: 19 # We have 19 different observations (POS / LINVEL / LINACC / ANG / ANGVEL / Rotor speed)

  # Normalized action
  action:
    rpm_max: 1.0
    rpm_min: -1.0

  # Env configuration
  init_motor_speed: 640
  range_motor_speed: 640

  init_linear_speed_vector:
    x: 0.0
    y: 0.0
    z: 0.0
  init_angular_turn_speed: 0.0 # Initial angular speed in which we start each episode

  work_space: # 3D cube in which drone is allowed to move
    x_max: 5.0
    x_min: -5.0
    y_max: 5.0
    y_min: -5.0
    z_max: 17.0
    z_min: 7.0

  max_roll: 1.57 # Max roll after which we end the episode
  max_pitch: 1.57 # Max roll after which we end the episode
  max_yaw: 3.14 # Max yaw, its 4 because its bigger the pi, its a complete turn actually the maximum

  desired_pose:
    x: 0.0
    y: 0.0
    z: 12.0

  desired_point_epsilon: 0.5 # Error acceptable to consider that it has reached the desired point

  reward:
    Ca: 0.5 # Constant alive bonus
    Cx: -0.008 # Positional penalty
    Cv: -0.0001 # Velocity Penalty
    Comega: -0.0003 # Angular velocity penalty

  task_and_robot_environment_name: 'HummingbirdHoverTaskEnvPPO-v2'
  ros_ws_abspath: '/home/ubuntu/catkin_ws'

  # Dont forget to change the path
